disabled = false
languageCode = 'tr-TR'
languageName = 'Turkish'
title = 'Fethullah Gulen Legacy Foundation'
copyright = """Designed with [Hugo](https://gohugo.io/) by [Ludovico Caluori](https://github.com/ololiuhqui) ğŸ¨ \n
 Licensed under [MIT license](https://github.com/ololiuhqui/magnolia-free-hugo-theme/blob/main/LICENSE.md) ğŸ“„""" # Please leave this here to give me and the tools i used some credit for the work, or BuyMeACoffee and change or remove the copyrightlink below :)
contentDir = "content/tr"

[params]
  subtitle = "Sorumluluk & ÅeffaflÄ±k" 
  # PAGES
  [params.homepage]
    ###
    preTitle = 'Sorumluluk & ÅeffaflÄ±k'
    title = "Fethullah Gulen Legacy Foundation"
    # You can use some markdown safely here as long as you don't include line breaks
    intro= """
### "Fethullah GÃ¼len Legacy Foundation (FGLF), dÃ¼nya Ã§apÄ±nda saygÄ± duyulan bir alim, eÄŸitimci, barÄ±ÅŸ savunucusu ve hayÄ±rsever olan Fethullah GÃ¼len'in deÄŸerlerini korumak, tanÄ±tmak ve muhafaza etmek amacÄ±yla kurulmuÅŸ kÃ¢r amacÄ± gÃ¼tmeyen bir kuruluÅŸtur."
___

**Evrensel eÄŸitim, manevi geliÅŸim, dinler arasÄ± diyalog ve insanlÄ±ÄŸa barÄ±ÅŸÃ§Ä±l hizmet deÄŸerlerine** dayanan vakÄ±f, 100'den fazla Ã¼lkede binlerce okula, insani yardÄ±m giriÅŸimine ve sivil toplum projesine ilham kaynaÄŸÄ± olmuÅŸ bir mirasÄ± ileriye taÅŸÄ±mak iÃ§in Ã§alÄ±ÅŸmaktadÄ±r. GÃ¼len'in hayatÄ± ve Ã¶ÄŸretileri, Ä°slami ahlak, Tasavvuf maneviyatÄ±, bilimsel araÅŸtÄ±rma ve sivil sorumluluÄŸun bir sentezini yansÄ±tmaktadÄ±r. VakÄ±f, hesap verebilirlik, ÅŸeffaflÄ±k ve etik liderliÄŸi vurgulayan programlar aracÄ±lÄ±ÄŸÄ±yla, bireyleri ve topluluklarÄ± daha barÄ±ÅŸÃ§Ä±l, kapsayÄ±cÄ± ve adil bir dÃ¼nya inÅŸa etmeleri iÃ§in gÃ¼Ã§lendirmeyi amaÃ§lamaktadÄ±r.

**VakÄ±f, bu misyonunu ÅŸu yollarla ilerletir:**

* AraÅŸtÄ±rma, yayÄ±nlar ve arÅŸiv projeleri
* Sivil katÄ±lÄ±m ve sosyal sorumluluk kampanyalarÄ±
* GÃ¼len'e baÄŸlÄ± kurumlarÄ±n denetimi
        """

[params.about]
  title = "HakkÄ±mÄ±zda"
 description = "HakkÄ±mÄ±zda"

[params.office]
  missionTitle = "Misyonumuz"
  missionStatement = """ Fethullah GÃ¼len'in entellektÃ¼el, manevi ve kÃ¼ltÃ¼rel mirasÄ±nÄ±; yasal yollar, araÅŸtÄ±rma, kamu savunuculuÄŸu ve sivil katÄ±lÄ±m aracÄ±lÄ±ÄŸÄ±yla etik liderliÄŸi, ÅŸeffaflÄ±ÄŸÄ±, sosyal sorumluluÄŸu, hukukun Ã¼stÃ¼nlÃ¼ÄŸÃ¼ne saygÄ±yÄ± ve hesap verebilirliÄŸi geliÅŸtirerek insanlÄ±ÄŸa hizmet yolunda korumak, yaÅŸatmak ve uygulamak. """
  visionTitle = "Vizyonumuz"
  visionStatement = """ EÄŸitimin hizmete ilham verdiÄŸi, bilginin merhametle birleÅŸtiÄŸi, bilimin inanÃ§la uyum iÃ§inde olduÄŸu ve farklÄ±lÄ±klarÄ±n karÅŸÄ±lÄ±klÄ± saygÄ±yla kucaklandÄ±ÄŸÄ± kapsayÄ±cÄ± bir dÃ¼nyada; ÅŸeffaflÄ±k ve hesap verebilirliÄŸin toplumumuzun standartlarÄ±nÄ± aÅŸtÄ±ÄŸÄ±, bireyleri ve toplumlarÄ± bilgelik, diyalog ve ortak insani deÄŸerler aracÄ±lÄ±ÄŸÄ±yla geliÅŸmeleri iÃ§in gÃ¼Ã§lendiren kurumlar. """
  teamTitle = "Ekibimizle tanÄ±ÅŸÄ±n!"
  title = "HakkÄ±mÄ±zda"
  description = "HakkÄ±mÄ±zda"
  [params.office.list]
    [params.office.list.0]
      name= "Fatih Yanik"
      title= "President"
      bio= """ <p>VakfÄ±n BaÅŸkanÄ± olarak Fatih YanÄ±k, yÃ¶netim kuruluna baÅŸkanlÄ±k etmekte, medya iliÅŸkilerini denetlemekte ve kuruluÅŸun programlarÄ± ile faaliyetlerine vizyon ve yÃ¶n vermektedir. Birden fazla eyalette inanÃ§ iÃ§i ve dinler arasÄ± diyalog koordinatÃ¶rÃ¼ olarak gÃ¶rev yapmÄ±ÅŸ ve Hizmet Hareketi iÃ§inde yedi yÄ±lÄ± aÅŸkÄ±n bir sÃ¼re genÃ§lik mentoru olarak gÃ¶nÃ¼llÃ¼ Ã§alÄ±ÅŸarak Amerika BirleÅŸik Devletleri genelinde kamplar ve etkinlikler dÃ¼zenlemiÅŸtir.</p>
<p>Fatih, Hawaii Ãœniversitesi'nden YaratÄ±cÄ± Medya alanÄ±nda lisans derecesine sahiptir ve ÅŸu anda Respect Graduate School'da Ä°slam AraÅŸtÄ±rmalarÄ± alanÄ±nda yÃ¼ksek lisans eÄŸitimine devam etmektedir. Profesyonel olarak, kÃ¢r amacÄ± gÃ¼tmeyen bir kamuya aÃ§Ä±k televizyon istasyonu olan Ê»ÅŒlelo Community Television'da Ã¼Ã§ yÄ±l Ã§alÄ±ÅŸmÄ±ÅŸ olup, ÅŸu anda ulusal olarak tanÄ±nan, kÃ¢r amacÄ± gÃ¼tmeyen bir medya kuruluÅŸu olan PBS'de KÄ±demli YayÄ±n MÃ¼hendisi olarak gÃ¶rev yapmaktadÄ±r.</p>
<p>En genÃ§ kurucu Ã¼ye olarak Fatih, enerjik ve taze bir yaklaÅŸÄ±ma sahiptir. KÃ¢r amacÄ± gÃ¼tmeyen medya alanÄ±ndaki kapsamlÄ± deneyimi ve Hizmet Hareketi'ndeki yÄ±llara dayanan taban koordinasyonuyla Fatih, VakÄ±f'taki rolÃ¼ne teknik uzmanlÄ±k, liderlik ve toplumsal katÄ±lÄ±mÄ±n eÅŸsiz bir karÄ±ÅŸÄ±mÄ±nÄ± getirmektedir.</p> """
      imageSrc = "https://drive.google.com/thumbnail?id=15_xwLYnCNJPSGc0fqXOEYxGlYSv7-jjk&sz=w1000"
    [params.office.list.1]
      name= "Murtaza Ozdemir"
      title= "Secretary"
      bio= """
**EÄŸitim TeknoloÄŸu â€¢ Bilgisayar ProgramcÄ±sÄ± â€¢ Veri UzmanÄ±**

**Murtaza Ã–zdemir, 1983 yÄ±lÄ±nda ortaokul Ã¶ÄŸrencisiyken** tanÄ±ÅŸtÄ±ÄŸÄ± eÄŸitim, hizmet ve adalet ilkelerinden ilham alarak hayatÄ±nÄ± **Hizmet Hareketi'ne adamÄ±ÅŸ bir savunucusudur.** Fethullah GÃ¼len'in Ã¶ÄŸretilerinden derinden ilham alan Ã–zdemir, kariyerini dÃ¼ÅŸÃ¼nceli liderlik, veriye dayalÄ± karar alma ve teknolojinin etik kullanÄ±mÄ± yoluyla eÄŸitimi ilerletmeye adamÄ±ÅŸtÄ±r. 30 yÄ±lÄ± aÅŸkÄ±n bir sÃ¼redir eÄŸitime ve Hizmet felsefesine adanmÄ±ÅŸ olan Murtaza, kendini farklÄ± topluluklardaki genÃ§leri besleme ve gÃ¼Ã§lendirme gibi anlamlÄ± bir gÃ¶reve vakfetmiÅŸtir.
**1995** yÄ±lÄ±nda Ä°stanbul'da **BoÄŸaziÃ§i Ãœniversitesi Matematik BÃ¶lÃ¼mÃ¼'nden** mezun olduktan sonra, Murtaza hayatÄ±nÄ± uluslararasÄ± sÄ±nÄ±rlarda eÄŸitime adamak iÃ§in hemen yurt dÄ±ÅŸÄ±na Ã§Ä±kmÄ±ÅŸtÄ±r. O zamandan beri sÃ¼rekli olarak TÃ¼rkiye dÄ±ÅŸÄ±nda yaÅŸamÄ±ÅŸ ve Ã§alÄ±ÅŸmÄ±ÅŸ, bir eÄŸitim kurumundan diÄŸerine geÃ§erek her zaman Ã¶ÄŸrenmeyi, karakter geliÅŸimini ve kÃ¼ltÃ¼rlerarasÄ± anlayÄ±ÅŸÄ± teÅŸvik etme hizmetinde bulunmuÅŸtur. Daha sonra ABD, New Jersey'deki William Paterson Ãœniversitesi'nden **EÄŸitim Teknolojileri alanÄ±nda YÃ¼ksek Lisans** derecesi almÄ±ÅŸtÄ±r.
Hem sÄ±nÄ±f iÃ§i eÄŸitim hem de eÄŸitim liderliÄŸi alanÄ±nda onlarca yÄ±llÄ±k tecrÃ¼besiyle Murtaza, Hizmet'in bilgi yoluyla insanlÄ±ÄŸa hizmet etme misyonunun rehberliÄŸinde, sÃ¼rekli olarak akademik mÃ¼kemmellik ve sivil sorumluluÄŸun kesiÅŸim noktasÄ±nda Ã§alÄ±ÅŸmÄ±ÅŸtÄ±r.
Profesyonel yolculuÄŸu, aÅŸaÄŸÄ±dakiler de dahil olmak Ã¼zere hem ulusal hem de uluslararasÄ± kurumlarda etkili roller iÃ§ermiÅŸtir:
* **SMU Pribadi**, Cakarta, Endonezya
* **Horizon Science Academy**, Ohio, ABD
* **Wisconsin Career Academy**, Wisconsin, ABD
* **Paterson Charter School for Science & Technology**, New Jersey, ABD
* **Bergen Arts and Science Charter School**, New Jersey, ABD
* **iLearn Schools**, New Jersey, ABD

Bu rolleri boyunca Murtaza, eÄŸitimde yeniliÄŸe olan baÄŸlÄ±lÄ±ÄŸÄ±, kapsayÄ±cÄ± ve iÅŸbirlikÃ§i Ã¶ÄŸrenme ortamlarÄ±nÄ± teÅŸvik etmesi ve teknoloji ile verinin stratejik kullanÄ±mÄ± yoluyla eÄŸitimcileri gÃ¼Ã§lendirmesiyle tanÄ±nmÄ±ÅŸtÄ±r. LiderliÄŸi, Ã¶ÄŸrenci merkezli, gelecek odaklÄ± bir yaklaÅŸÄ±mla birleÅŸen hizmete yÃ¶nelik derin bir ahlaki baÄŸlÄ±lÄ±ÄŸÄ± yansÄ±tmaktadÄ±r.
EÅŸitlikÃ§i, deÄŸerlere dayalÄ± eÄŸitimin sadÄ±k bir savunucusu olmaya devam etmekte ve her projeyi Hizmet'in temel ideallerini gerÃ§ekleÅŸtirmeâ€”bireyleri bilgi, ÅŸefkat ve topluma amaÃ§lÄ± katkÄ± yoluyla yÃ¼kseltmeâ€”fÄ±rsatÄ± olarak gÃ¶rmektedir. """
      imageSrc = "https://drive.google.com/thumbnail?id=1wEjEON-TfL-r7BLTbH22TQKib_QjRxhu&sz=w1000"
    [params.office.list.2]
      name= "Mustafa ParDane"
      title= "Treasurer"
      bio= """VakfÄ±n Mali Ä°ÅŸler Sorumlusu (Veznedar) olarak Mustafa ParDane, yÃ¶netim kurulunun mali idaresine liderlik etmektedir. SorumluluklarÄ± arasÄ±nda tÃ¼m mali varlÄ±klarÄ±n, bÃ¼tÃ§elerin ve raporlamanÄ±n gÃ¶zetimini sÃ¼rdÃ¼rmek ve yÃ¶netim kuruluna mali strateji ve risk yÃ¶netimi konusunda danÄ±ÅŸmanlÄ±k yapmak bulunmaktadÄ±r. AyrÄ±ca, mali tablolarÄ±n, IRS Form 990'Ä±n ve denetimlerin hazÄ±rlanmasÄ±nÄ± denetlerken, organizasyon iÃ§in mali politikalar ve iÃ§ kontroller geliÅŸtirmektedir.

Mustafa, ilk yÄ±llarÄ±ndan itibaren bu kelimeyi duyarak kendini "Hizmet'in iÃ§inde doÄŸmuÅŸ" biri olarak gÃ¶rmektedir. BabasÄ± ona daha okuyamadan Barla'da KÃ¼Ã§Ã¼k SÃ¶zler'i hediye etmiÅŸ ve Fethullah GÃ¼len'i ilk kez Ã¼Ã§ yaÅŸ civarÄ±ndayken Erzurum'da gÃ¶rmÃ¼ÅŸtÃ¼r. Anaokulundan 12. sÄ±nÄ±fa kadar okuduÄŸu, Hizmet'e baÄŸlÄ± Aziziye Koleji mezunudur. Mustafa, BoÄŸaziÃ§i Ãœniversitesi'nden lisans derecesine sahip olup, Ã¼niversite yÄ±llarÄ± boyunca Hizmet Hareketi iÃ§inde Ã§eÅŸitli vazifelerde gÃ¶rev almÄ±ÅŸtÄ±r.

2015 yÄ±lÄ±nda ABD'ye taÅŸÄ±ndÄ±ktan sonra Mustafa, yazÄ±lÄ±m mÃ¼hendisliÄŸi alanÄ±nda bir kariyere geÃ§iÅŸ yapmÄ±ÅŸtÄ±r. Google'a katÄ±lmÄ±ÅŸ ve ÅŸu anda Boulder, Colorado'da YazÄ±lÄ±m MÃ¼hendisi olarak Ã§alÄ±ÅŸmaktadÄ±r. Bir yÄ±llÄ±k kÃ¢r amacÄ± gÃ¼tmeyen kuruluÅŸ yÃ¶netim kurulu deneyimi ve Hizmet Hareketi'ne olan Ã¶mÃ¼r boyu sÃ¼ren baÄŸÄ±ndan gÃ¼Ã§ alan Mustafa, Vakfa analitik uzmanlÄ±k ve adanmÄ±ÅŸ hizmetin eÅŸsiz bir karÄ±ÅŸÄ±mÄ±nÄ± getirmektedir. """
      imageSrc = "https://drive.google.com/thumbnail?id=1hOsgTbadguRHCpuO3iuSdt5GRZo-5UH4&sz=w1000"

[params.contacts]
  title = "Ä°letiÅŸime geÃ§in!"
  formCallToAction = "Bize bir mesaj bÄ±rakÄ±n."
  socialCallToAction = "Bize sosyal medya hesaplarÄ±mÄ±zdan da ulaÅŸabilirsiniz." # These are the same as in [params.social]
  [params.contacts.form]
    formspreeLink = "https://formspree.io/f/xvgvwwbq" #subscribe to formspree and add the link for the form here
    firstname = "Ä°sim*"
    lastname = "Soyisim*"
    email = "E-mail*"
    phone = "Telefon numarasÄ±*"
    Inquiry = "MesajÄ±nÄ±z*"
    submitBtn = "GÃ¶nder"

[params.services]
  title = "SSS"
  description = """SÄ±kÃ§a Sorulan Sorular"""
  [params.services.list]
    [params.services.list.0]
      title= "Q1"
      description= "A1"
    [params.services.list.01]
      title = "Modular"
      description= "Hide and show some elements easily from the config file."
    [params.services.list.02]
      title = "Multilingual"
      description= "The default content language is english (it can be changed), but you can add as many languages as you want very easily, the theme includes an italian language example and a dropdown menÃ¹ for easily switching between languages. Permalinks can be localized in each language (eg. you can have `/contacts` for english and `/contatti` for italian)."
    [params.services.list.03]
      title = "Customizable"
      description= "The page content can be customized from within the config files."
    [params.services.list.04]
      title = "SEO ready"
      description= "Every page in /content has an easily customizable meta description and a unique meta title for better and easier indexing. The theme will use the image `static/img/meta-image` as meta image for Google, Meta and X."
    [params.services.list.05]
      title = "Google Analytics supported"
      description= "Insert your Google Analytics tag in the `config.toml` file and be ready to track your site performances easily."
    [params.services.list.06]
      title = "Google Maps Included"
      description= "The contact page can be easily customized by adding a google maps link to get directions towards your activity location."

[params.socials]
  enabled = true # enables/disables the whole social section in the footer
  callToAction= "Get connected with us on social networks >"
      [[params.socials.link]]
        name = "twitter-x"
        link = "https://x.com/gulenlegacy"
      # [[params.socials.link]]
      #   name = "linkedin"
      #   link = ""
      # [[params.socials.link]]
      #   name = "whatsapp"
      #   link = ""
      # You can add other socials here by copypasting the above section and
      # selecting the right name for the icon from here https://icons.getbootstrap.com/

[params.footer]
  # extraDescription1 = "Straight outta Scranton city"
  # extraDescription2 = "VAT No. 0000000000"
  [params.footer.navigate]
  heading = "Navigasyon"
  [params.footer.contacts]
  enabled = true # enables/disables the whole contacts section in footer
  heading = "Bize UlaÅŸÄ±n"
  address = "971 US Highway 202N Ste N Branchburg, NJ 08876 USA"
  mail = "contact@gulenlegacy.org"
  # phone = "+00 0000000"

[params.notfound]
  title = "404, page not found" # text for 404 page

[params.single] # for posts pages (visible only if posts are rendered)
  similarContent= "Similar Content"
  toc= "Table of Contents"

[menus]
# PageRef should refer to the "translationKey" in `/content/<page>` frontmatter, names can be changed freely
  [[menus.main]]
  name = "Anasayfa"
  pageRef = "/"
  weight = 1
  # [[menus.main]]
  # name = "SSS"
  # pageRef = "pages/faqs"
  # weight = 2
  [[menus.main]]
  name = "HakkÄ±mÄ±zda"
  pageRef = "pages/about"
  weight = 3
  [[menus.main]]
  name = "Ä°letiÅŸime geÃ§in!"
  pageRef = "pages/contacts"
  weight = 4
